use_frameworks!

target 'RangeCalendar_Example' do
  pod 'RangeCalendar', :path => '../'

  target 'RangeCalendar_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
