
# update_fastlane

default_platform(:ios)

platform :ios do
  
  ###-------------------------------- Tests ---------------------------###
	desc "Run tests"
	lane :test do
		scan(
			clean: true, code_coverage: true, scheme: "RangeCalendar-Example", devices: ["iPhone SE", "iPhone 8"]
		)

		slather(
			proj: "RangeCalendar.xcodeproj", workspace: "RangeCalendar.xcworkspace", scheme: "RangeCalendar-Example", source_directory: "../RangeCalendar/Classes", binary_basename: "RangeCalendar", travis: true, coveralls: true
		)
  	end

end